### ISSUE TITLE
Tracking: Form validation and errors

### ISSUE THREAD

**Issue by david-crespo** [oxidecomputer/console#1252]
Will add things to this list as they come up.

```[tasklist]
- [ ] https://github.com/oxidecomputer/console/issues/1233
- [ ] #1289
- [ ] #784
- [ ] https://github.com/oxidecomputer/omicron/issues/910
- [ ] https://github.com/oxidecomputer/console/issues/1786
- [ ] https://github.com/oxidecomputer/console/issues/1761
- [x] #1277
```

**Comment by david-crespo** [comment]
I think we are in pretty good shape on this finally.
