### ISSUE TITLE
Tracking: Access & IAM

### ISSUE THREAD

**Issue by benjaminleonard** [oxidecomputer/console#1328]
See [latest designs for Access & IAM](https://www.figma.com/file/NcUHVumfS9qzinnZhanL4F/Access-%26-IAM?node-id=1%3A2023&t=L2MmosHZX2J3Uqk6-1).

Updated based on our latest understanding of the IdP and access implementation for v1.

One thing we'll need to implement, perhaps only client-side, is a check to find the highest permission — since that is what we'll want to show in the table. The user can hover to see the full list of roles. This may need to be revisited as we expand the number of user roles.

```[tasklist]
- [ ] https://github.com/oxidecomputer/console/issues/1358
- [ ] https://github.com/oxidecomputer/console/issues/1357
- [ ] https://github.com/oxidecomputer/console/issues/1359
- [ ] https://github.com/oxidecomputer/console/issues/1360
- [ ] https://github.com/oxidecomputer/console/issues/1361
- [ ] https://github.com/oxidecomputer/console/issues/1362
- [ ] https://github.com/oxidecomputer/console/issues/1010
- [ ] List users in a group
- [ ] https://github.com/oxidecomputer/console/issues/2047
```

![ezgif-1-2ab19b54ed](https://user-images.githubusercontent.com/4020798/210535577-aa625675-ce24-4122-aec5-3c851e31d7f7.gif)
