### ISSUE TITLE
Tracking issue: supporting silo and project image actions

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#1559]
There are several loose ends to tie for images for MVP (not FCS)

- [ ] ability to view image details (may be implemented as a popup?)
- [ ] ability to delete image (silo image deletion depends on https://github.com/oxidecomputer/omicron/issues/3033)
- [ ] ability to copy image id (this applies to silo image only)
- [ ] ability to demote silo image (this applies to silo image only)
