### ISSUE TITLE
Support floating IP life-cycle events

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/console#1871]
This serves as a tracking issue and may be broken out into multiple sub-tickets.
The scope of support includes:

```[tasklist]
### Tasks
- [x] Add entries for api-mocks/floating-ip.ts
- [x] ~~Convert Networking page (currently just showing VPCs) to use tabs, with VPCs as first tab, Floating IPs as second tab~~ went with two separate pages instead
- [x] manage floating IP directly: list, create, delete
- [x] attach/detach IP of existing instances (depends on https://github.com/oxidecomputer/omicron/issues/4630)
- [ ] https://github.com/oxidecomputer/console/issues/1979
- [ ] https://github.com/oxidecomputer/console/issues/1980 (low priority)
```

**Comment by david-crespo** [comment]
Note that floating IPs are project-scoped so this will go under the project. I don’t know if we have designs for the nav but I could imagine this as part of a Networking entry in the sidebar alongside Disks, etc.

**Comment by benjaminleonard** [comment]
We should aim to get these into the next release. Me or @paryhin can work up designs but doesn't seem like it requires any patterns or components not used elsewhere already.

**Comment by david-crespo** [comment]
Closing because the core thing is done and the remaining work has its own issues.
